version: '3.7'

services:
  product-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: D@tN_etM_icr@Service2023
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
      MSSQL_TCP_PORT: 1433
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    volumes:
      - sql-data:/var/opt/mssql/data
    ports:
      - "1433:1433"
  
  product-webapi:
    image: productwebapi
    build:
      context: ./ProductService
      dockerfile: Dockerfile
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
    depends_on:
      - product-sql-server
volumes:
  sql-data: